
promise-test:
	csc promise-test.scm
	mv promise-test executables/
	./executables/promise-test

collatz-test:
	csc collatz-test.scm
	mv collatz-test executables/
	./executables/collatz-test

continuations-test:
	csc continuations-test.scm
	mv continuations-test executables/
	./executables/continuations-test

test-all: promise-test collatz-test continuations-test
