

(import chicken scheme)

(use srfi-1 srfi-13)
(use test numbers)

(use commons streams microkanren reasoned-schemer)

(test-group "Vars generation"
 (test-fail (equal? (V 'V0) (V/gensym)))
 (test-fail (equal? (V 'V₁) (V/gensym)))
 (test-fail (equal? (V/gensym) (V/gensym)))
 (test 'V₄ (variable->symbol (V/gensym)))
 (test 'V₅ (variable->symbol (V/gensym))))

(test-group "Tautologies"
 (test '()  (stream:->list (run ✗)))
 (test-fail (run/with-symbols ∘ ✗))
 (test '(#t) (stream:->list (run ✓)))
 (test-assert (run/with-symbols ∘ ✓))
 (test '()
  (stream:->list (run (≡ 2 3))))
 (test '(#t)
  (stream:->list (run (≡ 3 3))))
 (test '()
  (stream:->list (run (fresh (v) ✗))))
 (test '(#t)
  (stream:->list (run (fresh (v) ✓))))
 (test '(#t)
  (stream:->list (run (fresh (v) (≡ v 3)))))
 (test '()
  (stream:->list (run (fresh (v) (∧ (≡ v 3) (≡ v 4)))))))

(test '(3)
 (stream:->list (run (v) (≡ v 3))))
(test '(3)
 (stream:->list (run (v) (≡ 3 v))))
(test '(3)
 (stream:->list (run (v) (≡ '(3 4) `(,v 4)))))
(test (list (R '▢ 0))
 (stream:->list (run (v) ✓)))
(test '(▢₀)
 ((get/variable->symbol stream:->list)
  (run (v) ✓)))
(test '((▢₀ ▢₁))
 ((get/variable->symbol stream:->list)
  (run (v w) ✓)))
(test '((▢₀ ▢₀))
 ((get/variable->symbol stream:->list)
  (run (v w) (≡ v w))))
(test '((▢₀ (((▢₀)))))
 ((get/variable->symbol stream:->list)
  (run (v w) (≡ `(((,v))) w))))

(test-group "Lists destructuring relations"
 (test '(())
  ((get/variable->symbol stream:->list)
   (run (v) (nullº v))))
 (test '(0)
  ((get/variable->symbol stream:->list)
   (run (l) (carº '(0 1 2 3) l))))
 (test '((1 2 3))
  ((get/variable->symbol stream:->list)
   (run (l) (cdrº '(0 1 2 3) l))))
 (test '((3 4))
  ((get/variable->symbol stream:->list)
   (run (v w) (consº v 4 `(3 . ,w)))))
 (test '(#t)
  ((get/variable->symbol stream:->list)
   (run (fresh (w) (pairº `(3 . ,w))))))
 (test '((▢₀ . ▢₁))
  ((get/variable->symbol stream:->list)
   (run (w) (pairº w)))))


(test-group "listº"
 (test '()
  ((get/variable->symbol stream:->list)
   (run (listº 3))))
 (test '(#t)
  ((get/variable->symbol stream:->list)
   (run (listº '()))))
 (test '(#t)
  ((get/variable->symbol stream:->list)
   (run (listº '()))))
 (test '(#t)
  ((get/variable->symbol stream:->list)
   (run (listº '(3 4)))))
 (test '(() (▢₀) (▢₀ ▢₁) (▢₀ ▢₁ ▢₂) (▢₀ ▢₁ ▢₂ ▢₃))
  ;((get/variable->symbol (list○take 5))
   (run/with-symbols 5 (l) (listº l))))
 ;)

(test '(tea cup)
 ((get/variable->symbol stream:->list)
  (run (v) (tea-cupº v))))
(test '((split pea) (red bean))
 ((get/variable->symbol stream:->list)
  (run (v w) (split-peaº v w))))
(test '((tea ▢₀) (#f tea) (cup ▢₀) (#f cup))
 ((get/variable->symbol stream:->list)
  (run (v w) (split-pea₁º v w))))


(test-group "appendº"
(test-assert 
 (run/with-symbols ∘ (appendº '(0 1 2) '(3 4 5) '(0 1 2 3 4 5))))
 (test '(#t)
  ((get/variable->symbol stream:->list)
   (run (appendº '(0 1 2) '(3 4 5) '(0 1 2 3 4 5)))))
 (test '((0 1 2 3 4 5))
  ((get/variable->symbol stream:->list)
   (run (v) (appendº '(0 1 2) '(3 4 5) v))))
 (test '((() (0 1 2 3 4 5))
         ((0) (1 2 3 4 5))
         ((0 1) (2 3 4 5))
         ((0 1 2) (3 4 5))
         ((0 1 2 3) (4 5))
         ((0 1 2 3 4) (5))
         ((0 1 2 3 4 5) ()))
  ((get/variable->symbol stream:->list)
   (run (v w) (appendº v w '(0 1 2 3 4 5)))))
 (test '(((0 1 2 3 4 5) ())
         ((1 2 3 4 5) (0))
         ((2 3 4 5) (0 1))
         ((3 4 5) (0 1 2))
         ((4 5) (0 1 2 3))
         ((5) (0 1 2 3 4))
         (() (0 1 2 3 4 5)))
  (run/with-symbols ∞ (v w) (appendº w v '(0 1 2 3 4 5)))))
  (test '(() 
          (○ ●) 
          (○ ○ ● ●) 
          (○ ● ○ ●) 
          (○ ○ ○ ● ● ●) 
          (○ ● ○ ○ ● ●) 
          (○ ○ ● ● ○ ●) 
          (○ ● ○ ● ○ ●) 
          (○ ○ ● ○ ● ●) 
          (○ ● ○ ○ ○ ● ● ●) 
          (○ ○ ● ● ○ ○ ● ●) 
          (○ ● ○ ● ○ ○ ● ●) 
          (○ ○ ○ ● ● ● ○ ●) 
          (○ ● ○ ○ ● ● ○ ●) 
          (○ ○ ● ● ○ ● ○ ●) 
          (○ ● ○ ● ○ ● ○ ●) 
          (○ ○ ○ ○ ● ● ● ●) 
          (○ ● ○ ○ ● ○ ● ●) 
          (○ ○ ● ● ○ ○ ○ ● ● ●) 
          (○ ● ○ ● ○ ○ ○ ● ● ●) 
          (○ ○ ○ ● ● ● ○ ○ ● ●) 
          (○ ● ○ ○ ● ● ○ ○ ● ●) 
          (○ ○ ● ● ○ ● ○ ○ ● ●) 
          (○ ● ○ ● ○ ● ○ ○ ● ●) 
          (○ ○ ● ○ ● ● ○ ●) 
          (○ ● ○ ○ ○ ● ● ● ○ ●) 
          (○ ○ ● ● ○ ○ ● ● ○ ●) 
          (○ ● ○ ● ○ ○ ● ● ○ ●) 
          (○ ○ ○ ● ● ● ○ ● ○ ●) 
          (○ ● ○ ○ ● ● ○ ● ○ ●) 
          (○ ○ ● ● ○ ● ○ ● ○ ●) 
          (○ ● ○ ● ○ ● ○ ● ○ ●) 
          (○ ○ ● ○ ○ ● ● ●) 
          (○ ● ○ ○ ○ ○ ● ● ● ●) 
          (○ ○ ● ● ○ ○ ● ○ ● ●) 
          (○ ● ○ ● ○ ○ ● ○ ● ●) 
          (○ ○ ○ ● ● ● ○ ○ ○ ● ● ●) 
          (○ ● ○ ○ ● ● ○ ○ ○ ● ● ●) 
          (○ ○ ● ● ○ ● ○ ○ ○ ● ● ●) 
          (○ ● ○ ● ○ ● ○ ○ ○ ● ● ●) 
          (○ ○ ● ○ ● ● ○ ○ ● ●) 
          (○ ● ○ ○ ○ ● ● ● ○ ○ ● ●)) 
   (run/with-symbols 42 (α) (dyckº α)))

